import { GameRoom } from "./game-engine";
// @ts-ignore - This file is generated by open-next during build
import { default as nextHandler } from "../.open-next/worker.js";

// Re-export Durable Object class so Cloudflare can find it
export { GameRoom };

// Export the default fetch handler from Next.js
export default {
  async fetch(request: Request, env: CloudflareEnv, ctx: ExecutionContext) {
    return nextHandler.fetch(request, env, ctx);
  }
} satisfies ExportedHandler<CloudflareEnv>;